author: John Fairhurst
author_url: http://github.com/johnfairh
copyright: Distributed under the MIT license.  Maintained by [John Fairhurst](mailto:johnfairh@gmail.com).
readme: README.md
products:
  - docs
  - docset
  - unresolved-json
  - undocumented-json
code_host: github
code_host_url: https://github.com/johnfairh/swift-sass
code_host_file_url: https://github.com/johnfairh/swift-sass/blob/main
clean: true
sdk: macosx
theme: fw2020
deployment_url: https://johnfairh.github.io/swift-sass/
build_tool: spm
modules:
  - Sass
  - DartSass
docset_module_name: swift-sass
title: Swift Sass v2.0.0
module_version: 2.0.0
merge_modules: true
custom_abstracts: SourceDocs/*md
topic_style: source-order-defs
remote_autolink:
  - url: https://swiftpackageindex.com/apple/swift-nio/main/
  - url: https://apple.github.io/swift-log/docs/current/Logging/
    modules: Logging
rewrite_link_urls:
  - https://github.com/johnfairh/swift-sass/blob/main
custom_groups:
  - name: Sass Compilation
    abstract: Main types for using the Sass compiler.
    topics:
      - name: Compiler
        children:
          - DartSass.Compiler
      - name: Inputs
        children:
          - Syntax
          - CssStyle
          - SourceMapStyle
          - CompilerMessageStyle
          - CompilerWarningLevel
      - name: Outputs
        children:
          - CompilerResults
          - CompilerMessage
          - CompilerError
          - Span

  - name: Custom Importers
    children:
      - name: Dart Sass
        children:
          - DartSass.Importer
          - DartSass.ImporterResults
          - DartSass.FilesystemImporter
          - DartSass.ImportResolver

  - name: Custom Functions
    children:
      - SassFunction
      - SassFunctionSignature
      - SassFunctionMap

  - name: SassScript
    topics:
      - name: Main types
        children:
          - SassValue
          - SassString
          - SassNumber
          - SassColor
          - SassConstants
          - SassList
          - SassArgumentList
          - SassMap
          - SassCalculation
          - SassMixin
      - name: Function object types
        children:
          - SassCompilerFunction
          - SassDynamicFunction
      - name: Less-commonly used types
        children:
          - SassValueVisitor
          - SassNull
          - SassBool

  - name: Errors
    abstract: Types thrown as errors -- see `CompilerError` too.
    children:
      - DartSass.ProtocolError
      - DartSass.LifecycleError
      - Sass.SassFunctionError

custom_defs:
  - name: DartSass.Compiler
    topics:
      - name: Initializers
        children:
          - init(eventLoopGroup:timeout:messageStyle:verboseDeprecations:warningLevel:importers:functions:)
          - init(eventLoopGroup:embeddedCompilerFileURL:embeddedCompilerFileArguments:timeout:messageStyle:verboseDeprecations:warningLevel:importers:functions:)
      - name: Compilation
        children:
          - compile(string:syntax:url:importer:outputStyle:sourceMapStyle:includeCharset:importers:functions:)
          - compile(fileURL:outputStyle:sourceMapStyle:includeCharset:importers:functions:)
      - name: Lifecycle
        children:
           - compilerProcessIdentifier
           - compilerName
           - compilerVersion
           - compilerPackageVersion
           - reinit()
           - shutdownGracefully()
      - name: Logging
        children:
          - logger

  - name: SassValue
    topics:
      - name: Sass properties
        children:
          - isNull
          - isTruthy
      - name: Downcasts
        children:
          - asString()
          - asNumber()
          - asColor()
          - asBool()
          - asMap()
          - asArgumentList()
          - asCompilerFunction()
          - asDynamicFunction()
          - asCalculation()
      - name: Sass listiness
        children:
          - listCount
          - arrayIndexFrom(sassIndex:)
          - valueAt(sassIndex:)
          - hasBrackets
          - separator
      - name: Misc
        children:
          - ==(SassValue, SassValue)
          - accept(visitor:)
          - hash(into:)
          - makeIterator()
          - description

